title: Aeration
description: A framework for resource innovation and adoption.
theme: jekyll-theme-midnight
markdown: GFM

relative_links:
  enabled: true
  collections: true

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false